services:
  postgres:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data